### PR TITLE
Added transparent widgets

### PR DESCRIPTION
**Pull request by Pfuenzle**
This pull requests adds four additional transparent widgets (shown in comparison to their non-transparent counterparts):

Transparent News: 
Screenshot_20190310-185920_hyperion

Dark Transparent News:
Screenshot_20190310-185956_hyperion

Transparent Schedule:
Screenshot_20190310-190032_hyperion

Dark Transparent Schedule:
Screenshot_20190310-190059_hyperion

I also made preview-images for the new widgets, but those probably aren't the best

preview_1
preview_2
preview_3

If you see any inconsistency in the added/changed code, please tell me. This is my first experience with Kotlin so I'm open for suggestions

#### The following code adjustments were necessary:

- Added files for 4 additional widgets
- Added new color file ("color_transparent.xml")
- Replaced "when"-statements in ScheduleWidgetUpdateWorker.kt and NewsWidgetUpdateWorker.kt with "if/else"

### CODE REVIEW

**Comment by rubengees** [comment]
Thanks for the contribution!

I am not quite sure if we want the additional complexity of having a transparent variant for each widget, especially since it does not look that different. do you know of other apps that do so?

**Comment by Pfuenzle** [comment]
I see your point there, at first I wanted to add a setting in which you can set the transparency of the widget, but I haven't really gotten that to work so far, so I began adding the four extra widgets

I have seen some weather apps that provide transparent widgets, and on xda-developers there's a thread with apps modified to make the widgets transparent.

They may not look that different, but for me a semi-transparent widget looks way cleaner, especially on a phone with a big screen, thats why I began to add the widgets. But thats just my opinion, I can understand if you wouldn't like to add additional widgets just for transparency. Should I create an Issue for this topic, so it can be discussed wether to add transparency and if so, how, with extra widgets or a widget-setting?

**Comment by rubengees** [comment]
A setting for that would be great! Or in general a settings screen for widgets. Dark/Light, the refresh interval and possibly more things could be also changed there. Would be great if you could investigate that! I have seen apps that have such a settings screen. Maybe we could have an icon for that to the left of the refresh icon.

> Should I create an Issue for this topic?

Ah no, we can discuess here, just for the future before you (or someone else) starts working on something which might not be merged as is.

**Comment by Pfuenzle** [comment]
Great, I will look into it then

**Pull request closed without merging**
